services:
  sonar:
    image: sonarqube:lts-community
    container_name: sonarqube
    restart: unless-stopped
    networks:
      - barbearia
    ports:
      - '9000:9000'
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: true
  postgres:
    image: postgres:14-alpine
    container_name: barbearia_bd
    restart: unless-stopped
    networks:
      - barbearia
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: barbearia
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: barbearia_redis
    restart: unless-stopped
    networks:
      - barbearia
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
  prometheus:
    image: prom/prometheus:latest
    container_name: barbearia_prometheus
    restart: unless-stopped
    networks:
      - barbearia
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
  grafana:
    image: grafana/grafana:latest
    container_name: barbearia_grafana
    restart: unless-stopped
    networks:
      - barbearia
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana

networks:
  barbearia:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
  prometheus_data:
  grafana_data: