services:
  sonar:
    image: sonarqube:lts-community
    container_name: sonarqube
    restart: unless-stopped
    networks:
      - barbearia
    ports:
      - '9000:9000'
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: true
  postgres:
    image: postgres:14-alpine
    container_name: barbearia_bd
    restart: unless-stopped
    networks:
      - barbearia
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: barbearia
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  barbearia:
    driver: bridge

volumes:
  postgres-data: