server:
  port: 8080

spring:
  application:
    name: barbearia
  datasource:
    url: jdbc:postgresql://localhost:5432/barbearia
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: ${EMAIL_HOST}
    port: 2525
    username: ${EMAIL_USER}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger/ui.html

api:
  security:
    token:
      secret: ${JWT_SECRET}

aws:
  region: ${AWS_REGION}
  secret-access-key: ${AWS_SECRET}
  access-key-id: ${AWS_KEY}