server:
  port: 8080

spring:
  application:
    name: barbearia
  datasource:
    url: jdbc:postgresql://localhost:5432/barbearia
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
  cache:
    type: redis
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger/ui.html

api:
  security:
    token:
      secret: ${JWT_SECRET}

aws:
  region: ${AWS_REGION}
  endpoint:
    secretsManager: ${SECRETS_ENDPOINT}
    s3: ${S3_ENDPOINT}

email:
  secret: ${EMAIL_SECRET}