server:
  port: 8080

spring:
  application:
    name: barbearia
  datasource:
    url: jdbc:postgresql://localhost:5432/barbearia
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger/ui.html

api:
  security:
    token:
      secret: ${JWT_SECRET}

aws:
  region: ${AWS_REGION}

email:
  secret: ${EMAIL_SECRET}